spring.application.name=LearningPlatformValidation

# Configuración de Base de Datos Oracle
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@//localhost:1521/xepdb1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:system}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:oracle123}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Logging
logging.level.root=INFO
logging.level.com.duoc.LearningPlatformValidation=DEBUG
logging.level.org.springframework.web=DEBUG
